apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: front
  replicas: {{ default 1 .Values.replicas }}
  template: 
    metadata:
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
        - npm run start;
        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 2
        resources: {}



