apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  selector:
    matchLabels:
      app: front
  replicas: 1
  template: 
    metadata:
      annotations:
        prometheus.io/scrape: "true"
      labels:
        app: front
    spec:
      containers:
      - name: front-container
        image: tmdwn0704/all-in-one-front:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        command: ["/bin/sh", "-c"]
        args:
        - serve -s build;

        envFrom:
        - configMapRef:
            name: front-url
        
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 5
          
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 2
        resources: {}



