apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-front
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: front
  ports:
  - name: http
    port: {{ .Values.service.clusterIP }}
    targetPort: 3000
    {{ if eq .Values.service.type NodePort | eq .Values.service.type LoadBalancer }}
    nodePort: {{ .Values.service.nodePort }}
    {{ end }}
  type: NodePort

