name: image-build-and-update

on:
  push:
    tags:
      - 'v*'
# on:
#   push:
#     branches: [ master ]
      
jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout 
      uses: actions/checkout@v2
      with:
        path: main

    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
      
    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}

    # - name: Build and push
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     file: ./Dockerfile
    #     push: true
    #     tags: |
    #       ${{ secrets.DOCKERHUB_USERNAME }}/all-in-one-front:latest
    #       ${{ secrets.DOCKERHUB_USERNAME }}/all-in-one-front:${{ env.RELEASE_VERSION }}
    #     cache-from: type=gha
    #     cache-to: type=gha,mode=max

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-image
    steps: 

    - name: Checkout 
      uses: actions/checkout@v2
      with:
        repository: sjoh0704/All-In-One
        ref: "master"
        path: manifest

    - name: Set version
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

    - name: update manifest
      run: |
        sed -i '/^  tag:/c\  tag: ${{ env.RELEASE_VERSION }}' manifest/chart/front/values.yaml

    - name: Add & Commit
      uses: EndBug/add-and-commit@v4.4.0
      with:
        add: 'manifest/chart/front/values.yaml'
        ref: "master"
        cwd: "./manifest"
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Push commit
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GITHUB_TOKEN }}
        branch: "master"
        force: true
        repository: "sjoh0704/All-In-One"

      

      
      
